# Generated by Django 4.2.16 on 2026-08-22 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0007_alter_campaign_cover_image_alter_campaignimage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('campaign_viewed', 'Campaign Viewed'), ('campaign_shared', 'Campaign Shared'), ('campaign_clicked', 'Campaign Clicked'), ('donation_started', 'Donation Started'), ('donation_amount_selected', 'Donation Amount Selected'), ('donation_completed', 'Donation Completed')], max_length=40)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='campaigns.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='events_even_created_7af6de_idx'), models.Index(fields=['type'], name='events_even_type_654a97_idx'), models.Index(fields=['campaign'], name='events_even_campaig_341f9c_idx'), models.Index(fields=['session_id'], name='events_even_session_51fb95_idx')],
            },
        ),
    ]
