# Generated by Django 4.2.16 on 2026-09-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('campaign_viewed', 'Campaign Viewed'), ('campaign_shared', 'Campaign Shared'), ('campaign_clicked', 'Campaign Clicked'), ('donation_started', 'Donation Started'), ('donation_amount_selected', 'Donation Amount Selected'), ('donation_completed', 'Donation Completed'), ('embed_viewed', 'Embed Viewed')], max_length=40),
        ),
    ]
