# Generated by Django 4.2.16 on 2026-07-21 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisionTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('current_state', models.TextField(blank=True)),
                ('implementation', models.TextField(blank=True)),
                ('short_term_vision', models.TextField(blank=True)),
                ('long_term_vision', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vision Topic',
                'verbose_name_plural': 'Vision Topics',
                'ordering': ['order', 'title'],
            },
        ),
    ]
