# Generated by Django 4.2.16 on 2026-06-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, help_text='Name for unauthenticated donors', max_length=300),
        ),
    ]
