# Generated by Django 4.2.16 on 2026-07-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='provider',
            field=models.CharField(choices=[('wave', 'Wave'), ('aps', 'APS Wallet')], default='wave', max_length=20),
        ),
    ]
