# Generated by Django 4.2.16 on 2026-07-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone',
            field=models.CharField(blank=True, help_text='Not required for card payments.', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='provider',
            field=models.CharField(choices=[('wave', 'Wave'), ('aps', 'APS Wallet'), ('card', 'Card')], default='wave', max_length=20),
        ),
    ]
