# Generated by Django 4.2.16 on 2026-07-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='gateway',
            field=models.CharField(default='modempay', max_length=20),
        ),
    ]
