# Generated by Django 4.2.16 on 2026-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_donation_phone_alter_donation_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
