# Generated by Django 4.2.16 on 2026-08-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_donation_refund_reason_donation_refunded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='provider',
            field=models.CharField(choices=[('wave', 'Wave'), ('aps', 'APS Wallet'), ('afrimoney', 'Afrimoney'), ('card', 'Card')], default='wave', max_length=20),
        ),
    ]
