# Generated by Django 4.2.16 on 2026-09-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_organization_cover_image_organization_description_and_more'),
        ('campaigns', '0010_alter_campaign_status'),
        ('donations', '0007_alter_donation_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_donations', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaigns.campaign'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('campaign__isnull', False), ('organization__isnull', True)), models.Q(('campaign__isnull', True), ('organization__isnull', False)), _connector='OR'), name='donation_exactly_one_destination'),
        ),
    ]
