# Generated by Django 4.2.16 on 2026-09-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_donation_organization_alter_donation_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
