# Generated by Django 4.2.16 on 2026-06-28 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0003_campaignreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='campaignreport',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='campaignreport',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
