# Generated by Django 4.2.16 on 2026-07-07 13:14

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/covers/', validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='campaignimage',
            name='image',
            field=models.ImageField(upload_to='campaigns/gallery/', validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='campaignupdateimage',
            name='image',
            field=models.ImageField(upload_to='campaign_updates/', validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[apps.core.validators.validate_image_size]),
        ),
    ]
