# Generated by Django 4.2.16 on 2026-07-16 10:08

import apps.core.validators
from django.db import migrations, models
import utils.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaign_cover_image_alter_campaignimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_paths.campaign_cover_image_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='campaignimage',
            name='image',
            field=models.ImageField(upload_to=utils.upload_paths.campaign_gallery_image_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='campaignupdateimage',
            name='image',
            field=models.ImageField(upload_to=utils.upload_paths.campaign_update_image_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_paths.category_image_path, validators=[apps.core.validators.validate_image_size]),
        ),
    ]
