# Generated by Django 4.2.16 on 2026-08-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaign_cover_image_alter_campaignimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
    ]
