# Generated by Django 4.2.16 on 2026-09-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
    ]
