# Generated by Django 4.2.16 on 2026-09-06 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload_paths
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0010_alter_campaign_status'),
        ('users', '0024_organization_cover_image_organization_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_type', models.CharField(choices=[('organization', 'Organization'), ('campaign', 'Campaign')], max_length=20)),
                ('name', models.CharField(help_text='Internal, organization-facing name (e.g. "Ramadan Poster").', max_length=200)),
                ('template', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('community', 'Community')], max_length=20)),
                ('design', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posters', to='users.organization')),
            ],
            options={
                'verbose_name': 'Poster',
                'verbose_name_plural': 'Posters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='fundraising.poster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PosterImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=utils.upload_paths.poster_image_path)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fundraising.poster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_type', models.CharField(choices=[('organization', 'Organization'), ('campaign', 'Campaign')], max_length=20)),
                ('name', models.CharField(help_text='Internal, organization-facing name (e.g. "Homepage Donation").', max_length=200)),
                ('layout', models.CharField(choices=[('card', 'Card'), ('compact', 'Compact'), ('wide', 'Wide'), ('horizontal', 'Horizontal'), ('progress_focused', 'Progress-focused')], default='card', max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embeds', to='users.organization')),
            ],
            options={
                'verbose_name': 'Embed',
                'verbose_name_plural': 'Embeds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='poster',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('campaign__isnull', False), ('destination_type', 'campaign'), ('organization__isnull', True)), models.Q(('campaign__isnull', True), ('destination_type', 'organization'), ('organization__isnull', False)), _connector='OR'), name='poster_exactly_one_destination'),
        ),
        migrations.AddConstraint(
            model_name='embed',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('campaign__isnull', False), ('destination_type', 'campaign'), ('organization__isnull', True)), models.Q(('campaign__isnull', True), ('destination_type', 'organization'), ('organization__isnull', False)), _connector='OR'), name='embed_exactly_one_destination'),
        ),
    ]
