# Generated by Django 4.2.16 on 2026-09-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='template',
            field=models.CharField(choices=[('square', 'Square'), ('story', 'Story'), ('wide', 'Wide')], max_length=20),
        ),
    ]
