# Generated by Django 4.2.16 on 2026-09-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_alter_poster_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='return_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
