# Generated by Django 4.2.16 on 2026-07-15 15:25

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nisab_basis', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], default='silver', max_length=10)),
                ('nisab_gold_grams', models.DecimalField(decimal_places=2, default=Decimal('87.48'), max_digits=8)),
                ('nisab_silver_grams', models.DecimalField(decimal_places=2, default=Decimal('612.36'), max_digits=8)),
                ('gold_price_per_gram', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('silver_price_per_gram', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('zakat_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.50'), help_text='Percentage of zakatable wealth owed once it reaches nisab. Classically fixed at 2.5%.', max_digits=5)),
                ('minimum_amount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Zakat Settings',
                'verbose_name_plural': 'Zakat Settings',
            },
        ),
    ]
