# Generated by Django 4.2.16 on 2026-07-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakatsettings',
            name='nisab_basis',
        ),
    ]
