# Generated by Django 4.2.16 on 2026-07-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_platformsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('wave', 'Wave'), ('aps', 'APS Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='provider',
            field=models.CharField(choices=[('wave', 'Wave'), ('aps', 'APS Wallet')], max_length=20),
        ),
    ]
