# Generated by Django 4.2.16 on 2026-07-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_provider_alter_payout_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='card_payments_enabled',
            field=models.BooleanField(default=False, help_text='Whether donors can pay by Visa/Mastercard via ModemPay.'),
        ),
    ]
