# Generated by Django 4.2.16 on 2026-07-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_provider_alter_payout_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='provider_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
