# Generated by Django 4.2.16 on 2026-07-18 16:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payout_provider_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='gmd_to_settlement_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('70.0000'), help_text='How many GMD equal 1 unit of the Stripe settlement currency above — e.g. 70 means D70 = 1 unit. Update this to match the real exchange rate; a stale rate over/undercharges every card donation.', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='modempay_enabled',
            field=models.BooleanField(default=True, help_text='Whether donors/campaign owners can use ModemPay (Wave/APS mobile money).'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_enabled',
            field=models.BooleanField(default=False, help_text='Whether donors can pay by card via Stripe. Requires Stripe API keys to already be configured in the environment — this switch only controls whether the (already-configured) gateway is offered.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_settlement_currency',
            field=models.CharField(default='usd', help_text='Currency Stripe actually charges the card in (Stripe does not support GMD).', max_length=3),
        ),
    ]
