# Generated by Django 4.2.16 on 2026-08-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_platformsettings_gmd_to_settlement_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='aps_enabled',
            field=models.BooleanField(default=True, help_text='Whether APS Wallet is offered as a donation method (requires ModemPay enabled above).'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='wave_enabled',
            field=models.BooleanField(default=True, help_text='Whether Wave is offered as a donation and withdrawal method (requires ModemPay enabled above).'),
        ),
    ]
