# Generated by Django 4.2.16 on 2026-08-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_platformsettings_aps_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='afrimoney_enabled',
            field=models.BooleanField(default=True, help_text='Whether Afrimoney is offered as a donation and withdrawal method (requires ModemPay enabled above).'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='provider',
            field=models.CharField(choices=[('wave', 'Wave'), ('aps', 'APS Wallet'), ('afrimoney', 'Afrimoney')], max_length=20),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='modempay_enabled',
            field=models.BooleanField(default=True, help_text='Whether donors/campaign owners can use ModemPay (Wave/APS/Afrimoney mobile money).'),
        ),
    ]
