# Generated by Django 4.2.16 on 2026-08-25 23:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_platformsettings_afrimoney_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='modempay_max_donation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Maximum single donation amount via ModemPay. Keep this at or below whatever ModemPay itself currently enforces on a payment intent, or donations in between will pass validation here and still get rejected by ModemPay.', max_digits=12),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='modempay_min_donation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Minimum single donation amount via ModemPay (Wave/APS/Afrimoney).', max_digits=12),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_max_donation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Maximum single donation amount via Stripe (card), in GMD. Not independently confirmed against a real Stripe limit -- adjust if Stripe rejects amounts below this.', max_digits=12),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='stripe_min_donation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Minimum single donation amount via Stripe (card), in GMD.', max_digits=12),
        ),
    ]
