# Generated by Django 4.2.16 on 2026-08-27 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_platformsettings_modempay_max_donation_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['gateway', 'event_id'], name='payments_we_gateway_98349b_idx')],
                'unique_together': {('gateway', 'event_id')},
            },
        ),
    ]
