# Generated by Django 4.2.16 on 2026-07-15 12:25

import apps.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Dolelma', max_length=100)),
                ('site_description', models.CharField(blank=True, default='Crowdfunding for The Gambia', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Transparent logo, used on light and dark surfaces (nav, footer).', null=True, upload_to='branding/', validators=[apps.core.validators.validate_image_size])),
                ('logo_with_background', models.ImageField(blank=True, help_text='Logo on its own solid background, used where a transparent logo needs backing (e.g. social sharing).', null=True, upload_to='branding/', validators=[apps.core.validators.validate_image_size])),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
