# Generated by Django 4.2.16 on 2026-07-16 10:08

import apps.core.validators
from django.db import migrations, models
import utils.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Transparent logo, used on light and dark surfaces (nav, footer).', null=True, upload_to=utils.upload_paths.site_logo_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_with_background',
            field=models.ImageField(blank=True, help_text='Logo on its own solid background, used where a transparent logo needs backing (e.g. social sharing).', null=True, upload_to=utils.upload_paths.site_logo_with_background_path, validators=[apps.core.validators.validate_image_size]),
        ),
    ]
