# Generated by Django 4.2.16 on 2026-06-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('banjul', 'Banjul'), ('kanifing', 'Kanifing'), ('brikama', 'Brikama'), ('mansakonko', 'Mansakonko'), ('kerewan', 'Kerewan'), ('kuntaur', 'Kuntaur'), ('janjanbureh', 'Janjanbureh'), ('basse', 'Basse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('premium', 'Premium User'), ('moderator', 'Moderator')], default='user', max_length=20),
        ),
    ]
