# Generated by Django 4.2.16 on 2026-06-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio_user_is_verified_user_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_payment_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='default_payment_provider',
            field=models.CharField(blank=True, choices=[('modempay', 'ModemPay'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('afrimoney', 'Afrimoney')], max_length=20),
        ),
    ]
