# Generated by Django 4.2.16 on 2026-07-07 13:14

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_notify_campaign_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.core.validators.validate_image_size]),
        ),
    ]
