# Generated by Django 4.2.16 on 2026-07-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_payment_provider',
            field=models.CharField(blank=True, choices=[('wave', 'Wave'), ('aps', 'APS Wallet')], max_length=20),
        ),
    ]
