# Generated by Django 4.2.16 on 2026-07-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_identityverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('premium', 'Premium User'), ('moderator', 'Moderator'), ('finance_officer', 'Finance Officer')], default='user', max_length=20),
        ),
    ]
