# Generated by Django 4.2.16 on 2026-07-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_google_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_total_raised',
            field=models.BooleanField(default=True, help_text='Whether total funds raised is shown on your public campaigner profile.'),
        ),
    ]
