# Generated by Django 4.2.16 on 2026-07-14 16:16

import apps.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_show_total_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], default='individual', max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_id_type', models.CharField(choices=[('national_id', 'National ID Card'), ('passport', 'Passport'), ('drivers_license', "Driver's License")], max_length=20)),
                ('contact_id_number', models.CharField(max_length=50)),
                ('contact_id_photo_front', models.ImageField(upload_to='org_verifications/', validators=[apps.core.validators.validate_image_size])),
                ('contact_id_photo_back', models.ImageField(blank=True, null=True, upload_to='org_verifications/', validators=[apps.core.validators.validate_image_size])),
                ('registration_document', models.ImageField(upload_to='org_verifications/', validators=[apps.core.validators.validate_image_size])),
                ('organization_photo', models.ImageField(upload_to='org_verifications/', validators=[apps.core.validators.validate_image_size])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_organization_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Verification',
                'verbose_name_plural': 'Organization Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_type', models.CharField(choices=[('religious', 'Religious Organization'), ('student_union', 'Student Union'), ('community', 'Community-Based Organization'), ('national_agency', 'National Agency'), ('media', 'Media Organization'), ('other', 'Other')], max_length=20)),
                ('contact_person_name', models.CharField(max_length=200)),
                ('phone_2', models.CharField(max_length=20)),
                ('recovery_email_1', models.EmailField(blank=True, max_length=254)),
                ('recovery_email_2', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/', validators=[apps.core.validators.validate_image_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
