# Generated by Django 4.2.16 on 2026-07-15 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_account_type_organizationverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(choices=[('phone', 'Primary Phone Number'), ('phone_2', 'Second Phone Number'), ('recovery_email_1', 'Recovery Email 1'), ('recovery_email_2', 'Recovery Email 2')], max_length=20)),
                ('current_value', models.CharField(blank=True, max_length=255)),
                ('proposed_value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_organization_change_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Change Request',
                'verbose_name_plural': 'Organization Change Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
