# Generated by Django 4.2.16 on 2026-07-16 10:08

import apps.core.validators
from django.db import migrations, models
import utils.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_organizationchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverification',
            name='id_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_paths.identity_photo_back_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='id_photo_front',
            field=models.ImageField(upload_to=utils.upload_paths.identity_photo_front_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_paths.organization_logo_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='organizationverification',
            name='contact_id_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_paths.organization_contact_id_back_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='organizationverification',
            name='contact_id_photo_front',
            field=models.ImageField(upload_to=utils.upload_paths.organization_contact_id_front_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='organizationverification',
            name='organization_photo',
            field=models.ImageField(upload_to=utils.upload_paths.organization_photo_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='organizationverification',
            name='registration_document',
            field=models.ImageField(upload_to=utils.upload_paths.organization_registration_document_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_paths.user_avatar_path, validators=[apps.core.validators.validate_image_size]),
        ),
    ]
