# Generated by Django 4.2.16 on 2026-08-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_termsacceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_payment_provider',
            field=models.CharField(blank=True, choices=[('wave', 'Wave'), ('aps', 'APS Wallet'), ('afrimoney', 'Afrimoney')], max_length=20),
        ),
    ]
