# Generated by Django 4.2.16 on 2026-08-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_organization_contact_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_total_raised',
            field=models.BooleanField(default=True, help_text='Whether total funds raised is shown on your public fundraiser profile.'),
        ),
    ]
