# Generated by Django 4.2.16 on 2026-08-27 00:05

import apps.core.validators
from django.db import migrations, models
import utils.storage
import utils.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_show_total_raised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationverification',
            name='organization_photo',
            field=models.ImageField(storage=utils.storage.VerificationDocumentStorage(), upload_to=utils.upload_paths.organization_photo_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='organizationverification',
            name='registration_document',
            field=models.ImageField(storage=utils.storage.VerificationDocumentStorage(), upload_to=utils.upload_paths.organization_registration_document_path, validators=[apps.core.validators.validate_image_size]),
        ),
    ]
