# Generated by Django 4.2.16 on 2026-09-06 13:44
# Hand-edited: the auto-generated single AddField for `slug` (unique=True,
# no default) isn't safe against existing Organization rows -- see the
# split below.

import apps.core.validators
from django.db import migrations, models
from django.utils.text import slugify
import utils.upload_paths


def backfill_organization_slugs(apps, schema_editor):
    Organization = apps.get_model('users', 'Organization')
    existing = set(Organization.objects.exclude(slug='').values_list('slug', flat=True))
    for org in Organization.objects.filter(slug__isnull=True).order_by('created_at'):
        base = slugify(org.organization_name) or 'organization'
        slug = base
        n = 1
        while slug in existing:
            slug = f'{base}-{n}'
            n += 1
        existing.add(slug)
        org.slug = slug
        org.save(update_fields=['slug'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_private_verification_document_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_paths.organization_cover_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
        # Step 1: add nullable+unique -- multiple NULLs are allowed under a
        # unique constraint (Postgres and SQLite both treat NULL as
        # distinct-from-itself), so this is safe against however many
        # Organization rows already exist, with no default needed.
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        # Step 2: backfill every existing row with a real, unique slug --
        # same slugify + collision-loop algorithm as Organization.save().
        migrations.RunPython(backfill_organization_slugs, noop_reverse),
        # Step 3: drop null=True now that every row has a real value,
        # landing on the same field shape as Campaign.slug.
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
