# Generated by Django 4.2.16 on 2026-09-06 19:19

import apps.core.validators
from django.db import migrations, models
import utils.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_organization_cover_image_organization_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationverification',
            name='organization_photo',
            field=models.ImageField(upload_to=utils.upload_paths.organization_photo_path, validators=[apps.core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='organizationverification',
            name='registration_document',
            field=models.ImageField(upload_to=utils.upload_paths.organization_registration_document_path, validators=[apps.core.validators.validate_image_size]),
        ),
    ]
