# Generated by Django 4.2.16 on 2026-08-27 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('platform_clearing', 'Platform Clearing (Payment Provider)'), ('platform_fees', 'Platform Fees Revenue'), ('campaign', 'Campaign Balance'), ('organization', 'Organization Balance'), ('user', 'User / Investor Balance'), ('suspense', 'Suspense / Manual Adjustments')], max_length=30)),
                ('code', models.SlugField(max_length=150, unique=True)),
                ('owner_type', models.CharField(blank=True, max_length=50)),
                ('owner_id', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(default='GMD', max_length=3)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('donation_received', 'Donation Received'), ('donation_refunded', 'Donation Refunded'), ('payout_completed', 'Payout Completed'), ('admin_adjustment', 'Admin Adjustment')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='GMD', max_length=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner_type', 'owner_id'], name='ledger_acco_owner_t_d59d88_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['type'], name='ledger_acco_type_cdd804_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['source_type', 'source_id'], name='ledger_tran_source__ca66e9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['entry_type'], name='ledger_tran_entry_t_0a85cd_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', '-created_at'], name='ledger_ledg_account_34c609_idx'),
        ),
    ]
