# Generated by Django 4.2.16 on 2026-08-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('users', 'Can access Users'), ('staff', 'Can access Staff'), ('dashboard', 'Can access Dashboard'), ('settings', 'Can access Settings'), ('campaigns_view', 'Can view Campaigns'), ('campaigns_moderate', 'Can moderate Campaigns'), ('categories', 'Can access Categories'), ('reports', 'Can access Reports'), ('verifications', 'Can access Verifications'), ('donations', 'Can access Donations'), ('finances', 'Can access Finances'), ('audit', 'Can access Audit')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
