# Generated by Django 4.2.16 on 2026-08-24 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_seed_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='adminresource',
            options={'default_permissions': (), 'managed': False, 'permissions': [('users_view', 'Can view Users'), ('users_edit', 'Can edit Users'), ('users_delete', 'Can delete Users'), ('staff_view', 'Can view Staff'), ('staff_create', 'Can create Staff'), ('staff_edit', 'Can edit Staff'), ('staff_delete', 'Can delete Staff'), ('roles_manage', 'Can manage Roles & Permissions'), ('dashboard_view', 'Can view Dashboard'), ('settings_edit', 'Can edit Settings'), ('campaigns_view', 'Can view Campaigns'), ('campaigns_moderate', 'Can moderate Campaigns'), ('categories_view', 'Can view Categories'), ('categories_create', 'Can create Categories'), ('categories_edit', 'Can edit Categories'), ('categories_delete', 'Can delete Categories'), ('reports_view', 'Can view Reports'), ('reports_edit', 'Can edit Reports'), ('verifications_view', 'Can view Verifications'), ('verifications_edit', 'Can edit Verifications'), ('donations_view', 'Can view Donations'), ('donations_edit', 'Can edit Donations'), ('finances_view', 'Can view Finances'), ('audit_view', 'Can view Audit')]},
        ),
    ]
