# Generated by Django 4.2.16 on 2026-08-22 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('user.logged_in', 'Logged In'), ('user.registered', 'Registered'), ('user.password_reset', 'Reset Password'), ('user.profile_updated', 'Updated Profile'), ('user.role_changed', "Changed User's Role"), ('user.account_deleted', 'Deleted Account'), ('staff.created', 'Created Staff Account'), ('campaign.created', 'Created Campaign'), ('campaign.updated', 'Updated Campaign'), ('campaign.deleted', 'Deleted Campaign'), ('campaign.published', 'Published Campaign'), ('campaign.unpublished', 'Unpublished Campaign'), ('campaign.rejected', 'Rejected Campaign'), ('report.status_changed', 'Updated Report'), ('verification.approved', 'Approved Verification'), ('verification.rejected', 'Rejected Verification'), ('donation.created', 'Created Donation'), ('donation.status_changed', 'Donation Status Changed'), ('payment.refunded', 'Refunded Payment'), ('payout.requested', 'Requested Payout'), ('payout.status_changed', 'Payout Status Changed')], max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['actor'], name='audit_audit_actor_i_17b775_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
