# Generated by Django 4.2.16 on 2026-08-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user.logged_in', 'Logged In'), ('user.registered', 'Registered'), ('user.password_reset', 'Reset Password'), ('user.profile_updated', 'Updated Profile'), ('user.role_changed', "Changed User's Role"), ('user.account_deleted', 'Deleted Account'), ('staff.created', 'Created Staff Account'), ('campaign.created', 'Created Campaign'), ('campaign.updated', 'Updated Campaign'), ('campaign.deleted', 'Deleted Campaign'), ('campaign.published', 'Published Campaign'), ('campaign.unpublished', 'Unpublished Campaign'), ('campaign.rejected', 'Rejected Campaign'), ('report.status_changed', 'Updated Report'), ('verification.approved', 'Approved Verification'), ('verification.rejected', 'Rejected Verification'), ('donation.created', 'Created Donation'), ('donation.status_changed', 'Donation Status Changed'), ('payment.refunded', 'Refunded Payment'), ('payout.requested', 'Requested Payout'), ('payout.status_changed', 'Payout Status Changed'), ('organization.created', 'Created Organization'), ('organization.ownership_transferred', 'Transferred Ownership'), ('organization.member_removed', 'Removed Member'), ('organization.member_role_changed', "Changed Member's Role")], max_length=40),
        ),
    ]
