# Generated by Django 4.2.16 on 2026-09-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('donation_received', 'Donation Received'), ('campaign_approved', 'Campaign Approved'), ('campaign_rejected', 'Campaign Rejected'), ('campaign_suspended', 'Campaign Suspended'), ('payout_processed', 'Payout Processed'), ('campaign_update', 'Campaign Update'), ('goal_reached', 'Goal Reached'), ('donation_refunded', 'Donation Refunded'), ('campaign_expired', 'Campaign Expired')], max_length=30),
        ),
    ]
